"""empty message

Revision ID: fccf5f217af0
Revises: 4d1183df8536
Create Date: 2021-04-14 13:12:41.807400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fccf5f217af0'
down_revision = '4d1183df8536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question')
    # ### end Alembic commands ###
