"""empty message

Revision ID: 8128e8ae7b04
Revises: fccf5f217af0
Create Date: 2021-04-14 13:18:25.845169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8128e8ae7b04'
down_revision = 'fccf5f217af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('repo_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'questions', 'questions_repo', ['repo_id'], ['id'])
    op.drop_column('questions', 'subcategory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('subcategory', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'repo_id')
    # ### end Alembic commands ###
