"""empty message

Revision ID: c4d6634cd33e
Revises: 4880e68c87cc
Create Date: 2021-04-14 12:44:26.570871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d6634cd33e'
down_revision = '4880e68c87cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions_repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('type', sa.String(length=250), nullable=False),
    sa.Column('subcategory', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('questions_repo')
    op.drop_column('questions', 'question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_table('questions_repo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('subcategory', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='questions_repo_pkey')
    )
    op.drop_table('questions_repos')
    # ### end Alembic commands ###
