"""empty message

Revision ID: 32ac9ec9d668
Revises: 0c36dc787e6c
Create Date: 2021-04-14 23:04:44.944202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ac9ec9d668'
down_revision = '0c36dc787e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions_repo', sa.Column('subcategory', sa.String(length=250), nullable=True))
    op.add_column('questions_repo', sa.Column('type', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions_repo', 'type')
    op.drop_column('questions_repo', 'subcategory')
    # ### end Alembic commands ###
